all: bottled_nin.png parallel_nin.png

parallel_nin.png: parallel_nin.dot
	dot parallel_nin.dot -Tpng -o parallel_nin.png
	
bottled_nin.png: bottled_nin.dot
	dot bottled_nin.dot -Tpng -o bottled_nin.png
